global using Commons.Logging;
global using ExternalAPI.DTOs;
global using Infrastructure.Middleware;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Serilog;
global using Setting.Application;
global using Setting.Application.feature.v1.Queries.GetCategorySettings;
global using Setting.Domain.Enums;
global using Setting.Infrastructure;
global using Setting.Infrastructure.Persitence;
global using Shared.SeedWorks;
global using System.Net;global using System.Reflection;
global using Infrastructure.Extensions;
global using Setting.Service.Infrastructures;
global using Setting.Service.Infrastructures.Endpoints;
