global using API.Intergration.Config.Service.Extensions;
global using API.Intergration.Config.Service.v1.DTOs;
global using API.Intergration.Config.Service.v1.Query;
global using API.Intergration.Config.Service.v1.Services;
global using Commons.Logging;
global using Contracts.Commons.Interfaces;
global using Dapper.Extensions;
global using Dapper.Extensions.PostgreSql;
global using Grpc.Core;
global using Infrastructure.Extensions;
global using Infrastructure.Middleware;
global using Infrastructure.ORMs.Dapper;
global using Serilog;
global using ILogger = Serilog.ILogger;
