global using Authenticate.Service.Extensions;
global using Authenticate.Service.Infrastructure.Endpoints;
global using Authenticate.Service.Services;
global using Authenticate.Verify.Service;
global using Commons.Logging;
global using Contracts.Commons.Interfaces;
global using Dapper.Extensions;
global using Dapper.Extensions.MSSQL;
global using Grpc.Core;
global using Infrastructure.Commons;
global using Infrastructure.Extensions;
global using Infrastructure.Middleware;
global using Infrastructure.ORMs.Dapper;
global using Microsoft.IdentityModel.Tokens;
global using Serilog;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using static Authenticate.Verify.Service.AuthenticateVerify;
global using ILogger = Serilog.ILogger;