global using Contracts.Commons.Constants;
global using Contracts.Commons.Interfaces;
global using Infrastructure.Commons;
global using Infrastructure.Helper;
global using Message.Domain.Entities;
global using Message.Domain.Models;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using MongoDB.Driver;
global using Newtonsoft.Json;
global using System;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using ILogger = Serilog.ILogger;