global using Commons.Logging;
global using Commons.Pagination;
global using Contracts.Commons.Constants;
global using Contracts.Commons.Interfaces;
global using Dapper.Extensions;
global using Dapper.Extensions.MySql;
global using Grpc.Core;
global using Infrastructure.Commons;
global using Infrastructure.Extensions;
global using Infrastructure.Helper;
global using Infrastructure.Middleware;
global using Infrastructure.ORMs.Dapper;
global using Microsoft.EntityFrameworkCore;
global using Post.API.Protos;
global using Post.Application.Commons.Interfaces;
global using Post.Infrastructure.Persistence;
global using Post.Infrastructure.Persistence.Query;
global using Post.Infrastructure.Repository;
global using Post.Service.Extentions;
global using Post.Service.Infrastructure.Endpoints;
global using Post.Service.Services;
global using Serilog;
global using static Post.API.Protos.PostApiService;
global using ILogger = Serilog.ILogger;