global using API.Intergration.Config.Service.Protos;
global using Authenticate.Verify.Service;
global using Calzolari.Grpc.AspNetCore.Validation.Internal;
global using Consul;
global using Contracts.Commons.Constants;
global using Contracts.Commons.Interfaces;
global using ExternalAPI;
global using Grpc.Net.ClientFactory;
global using Infrastructure.Commons;
global using Infrastructure.Extensions;
global using Infrastructure.Factorys;
global using Infrastructure.Helper;
global using Infrastructure.Middleware;
global using Message.Application.Extensions;
global using Message.Application.Feature.v1.ApiConfigService;
global using Message.Domain.Entities;
global using Message.Domain.Models;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Serilog;
global using System.Net.Http.Headers;
global using System.Reflection;
global using static API.Intergration.Config.Service.Protos.ApiConfigGrpc;
global using static Authenticate.Verify.Service.AuthenticateVerify;global using Message.Application.Service;
global using Message.Application.Service.Interfaces;
global using Message.Application.Infrastructure.Dtos;
global using Commons.Pagination;
global using AutoMapper;
global using MongoDB.Driver;
global using Message.Application.Infrastructure.Helper;
global using ExternalAPI.Models;
global using Shared.Enums;
global using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;
