global using Calzolari.Grpc.AspNetCore.Validation.Internal;
global using Commons.Logging;
global using Contracts.Commons.Constants;
global using Grpc.Core;
global using Infrastructure.Extensions;
global using Infrastructure.Middleware;
global using Newtonsoft.Json;
global using SearchPartners.Service.Extensions;
global using SearchPartners.Service.Helpers;
global using SearchPartners.Service.Infrastructure.Endpoints;
global using SearchPartners.Service.Services;
global using Serilog;
global using Shared.DTOs;
global using static SearchPartners.Service.SearchPartnerService;
global using ILogger = Serilog.ILogger;