global using Contracts.Commons.Interfaces;
global using FluentValidation;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using Shared.Enums;
global using Shared.SeedWorks;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Net;
global using System.Reflection;
global using System.Threading;
global using System.Threading.Tasks;
global using User.Application.Commons.Interfaces;
global using User.Application.Commons.Models;
global using User.Domain.Entities;
global using UserErrorMessages = User.Application.ErrorMessages.ErrorMessages;
