global using Post.Infrastructure.Persistence;
global using Post.API.Services;
global using Infrastructure.Helper;
global using Post.Application.Commons.Interfaces;
global using Infrastructure.Commons;
global using Infrastructure.ORMs.Dapper;
global using Post.Infrastructure.Repository;
global using static Post.API.Protos.PostApiService;
global using Post.Infrastructure.Persistence.Query;
global using Grpc.Core;
global using ILogger = Serilog.ILogger;
global using Serilog;
global using Post.API.Infrastructure;
global using Commons.Logging;
global using Infrastructure.ORMs.Dappers.Interfaces;
global using Dapper.Extensions.MySql;
global using Infrastructure.Extensions;
global using Dapper.Extensions;
global using Newtonsoft.Json;
global using Post.API.Extentions;
global using Contracts.Commons.Interfaces;
global using Commons.Pagination;
global using Infrastructure.ORMs.Dappers;
global using Post.API.Protos;
