global using Commons.Logging;
global using Commons.Pagination;
global using Contracts.Commons.Interfaces;
global using Dapper.Extensions;
global using Dapper.Extensions.MySql;
global using Grpc.Core;
global using Infrastructure.Commons;
global using Infrastructure.Extensions;
global using Infrastructure.Helper;
global using Infrastructure.ORMs.Dapper;
global using Microsoft.EntityFrameworkCore;
global using Newtonsoft.Json;
global using Post.API.Protos;
global using Post.Application.Commons.Interfaces;
global using Post.Infrastructure.Persistance;
global using Post.Infrastructure.Persistance.Query;
global using Post.Infrastructure.Repository;
global using Serilog;
global using static Post.API.Protos.PostApiService;
global using ILogger = Serilog.ILogger;