version: '3.8'

services:
    minioResource:
        container_name: minioResource
        environment:
            MINIO_ROOT_USER: root
            MINIO_ROOT_PASSWORD: 0967442142Az*
            MINIO_ACCESS_KEY: /r8zCJk8iibBn7Qe01lIsWsreJdEBQKJTQA+vLh96Zk=
            MINIO_SECRET_KEY: YYZ6wpaLgniyR06SCKyR+twE2wZhv2KAiXa5ShydXioopwXqLq/6uBJKiWQmXxJ/
        restart: always
        volumes:
            - minio_data:var/lib/minio/images/data
        ports:
            - "9000:9000"
            - "9001:9001"
        