global using API.Intergration.Config.Service.Protos;
global using Authenticate.Verify.Service;
global using Calzolari.Grpc.AspNetCore.Validation.Internal;
global using Commons.Logging;
global using Consul;
global using Contracts.Commons.Constants;
global using Contracts.Commons.Interfaces;
global using ExternalAPI;
global using Grpc.Net.ClientFactory;
global using Infrastructure.Commons;
global using Infrastructure.Configurations;
global using Infrastructure.Extensions;
global using Infrastructure.Factorys;
global using Infrastructure.Middleware;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using SearchPartners.Aggregate.Service.Extensions;
global using SearchPartners.Aggregate.Service.Infrastructure;
global using SearchPartners.Aggregate.Service.Infrastructure.Endpoints;
global using SearchPartners.Aggregate.Service.Infrastructure.Messages;
global using SearchPartners.Aggregate.Service.Services.v1.ApiConfigService;
global using SearchPartners.Aggregate.Service.Services.v1.Query.SearchPartners;
global using Serilog;
global using Shared.DTOs;
global using Shared.SeedWorks;
global using System.Net.Http.Headers;
global using System.Reflection;
global using static API.Intergration.Config.Service.Protos.ApiConfigGrpc;
global using static Authenticate.Verify.Service.AuthenticateVerify;
global using ILogger = Serilog.ILogger;
